countries = [
    {
        "country": "Afghanistan",
        "full_name": "The Islamic Republic of Afghanistan",
        "iso_code_2": "AF",
        "iso_code_3": "AFG",
    },
    {
        "country": "Åland Islands",
        "full_name": "Åland",
        "iso_code_2": "AX",
        "iso_code_3": "ALA",
    },
    {
        "country": "Albania",
        "full_name": "The Republic of Albania",
        "iso_code_2": "AL",
        "iso_code_3": "ALB",
    },
    {
        "country": "Algeria",
        "full_name": "The People's Democratic Republic of Algeria",
        "iso_code_2": "DZ",
        "iso_code_3": "DZA",
    },
    {
        "country": "American Samoa",
        "full_name": "The Territory of American Samoa",
        "iso_code_2": "AS",
        "iso_code_3": "ASM",
    },
    {
        "country": "Andorra",
        "full_name": "The Principality of Andorra",
        "iso_code_2": "AD",
        "iso_code_3": "AND",
    },
    {
        "country": "Angola",
        "full_name": "The Republic of Angola",
        "iso_code_2": "AO",
        "iso_code_3": "AGO",
    },
    {
        "country": "Anguilla",
        "full_name": "Anguilla",
        "iso_code_2": "AI",
        "iso_code_3": "AIA",
    },
    {
        "country": "Antarctica",
        "full_name": "Antarctica (all land and ice shelves south of the 60th parallel south)",
        "iso_code_2": "AQ",
        "iso_code_3": "ATA",
    },
    {
        "country": "Antigua and Barbuda",
        "full_name": "Antigua and Barbuda",
        "iso_code_2": "AG",
        "iso_code_3": "ATG",
    },
    {
        "country": "Argentina",
        "full_name": "The Argentine Republic",
        "iso_code_2": "AR",
        "iso_code_3": "ARG",
    },
    {
        "country": "Armenia",
        "full_name": "The Republic of Armenia",
        "iso_code_2": "AM",
        "iso_code_3": "ARM",
    },
    {
        "country": "Aruba",
        "full_name": "Aruba",
        "iso_code_2": "AW",
        "iso_code_3": "ABW"
    },
    {
        "country": "Australia",
        "full_name": "The Commonwealth of Australia",
        "iso_code_2": "AU",
        "iso_code_3": "AUS",
    },
    {
        "country": "Austria",
        "full_name": "The Republic of Austria",
        "iso_code_2": "AT",
        "iso_code_3": "AUT",
    },
    {
        "country": "Azerbaijan",
        "full_name": "The Republic of Azerbaijan",
        "iso_code_2": "AZ",
        "iso_code_3": "AZE",
    },
    {
        "country": "Bahamas",
        "full_name": "The Commonwealth of The Bahamas",
        "iso_code_2": "BS",
        "iso_code_3": "BHS",
    },
    {
        "country": "Bahrain",
        "full_name": "The Kingdom of Bahrain",
        "iso_code_2": "BH",
        "iso_code_3": "BHR",
    },
    {
        "country": "Bangladesh",
        "full_name": "The People's Republic of Bangladesh",
        "iso_code_2": "BD",
        "iso_code_3": "BGD",
    },
    {
        "country": "Barbados",
        "full_name": "Barbados",
        "iso_code_2": "BB",
        "iso_code_3": "BRB",
    },
    {
        "country": "Belarus",
        "full_name": "The Republic of Belarus",
        "iso_code_2": "BY",
        "iso_code_3": "BLR",
    },
    {
        "country": "Belgium",
        "full_name": "The Kingdom of Belgium",
        "iso_code_2": "BE",
        "iso_code_3": "BEL",
    },
    {
        "country": "Belize",
        "full_name": "Belize",
        "iso_code_2": "BZ",
        "iso_code_3": "BLZ",
    },
    {
        "country": "Benin",
        "full_name": "The Republic of Benin",
        "iso_code_2": "BJ",
        "iso_code_3": "BEN",
    },
    {
        "country": "Bermuda",
        "full_name": "Bermuda",
        "iso_code_2": "BM",
        "iso_code_3": "BMU",
    },
    {
        "country": "Bhutan",
        "full_name": "The Kingdom of Bhutan",
        "iso_code_2": "BT",
        "iso_code_3": "BTN",
    },
    {
        "country": "Bolivia (Plurinational State of)",
        "full_name": "The Plurinational State of Bolivia",
        "iso_code_2": "BO",
        "iso_code_3": "BOL",
    },
    {
        "country": "Bonaire",
        "full_name": "Bonaire, Sint Eustatius and Saba",
        "iso_code_2": "BQ",
        "iso_code_3": "BES",
    },
    {
        "country": "Sint Eustatius",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": ""
    },
    {
        "country": "Saba",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": ""
    },
    {
        "country": "Bosnia and Herzegovina",
        "full_name": "Bosnia and Herzegovina",
        "iso_code_2": "BA",
        "iso_code_3": "BIH",
    },
    {
        "country": "Botswana",
        "full_name": "The Republic of Botswana",
        "iso_code_2": "BW",
        "iso_code_3": "BWA",
    },
    {
        "country": "Bouvet Island",
        "full_name": "Bouvet Island",
        "iso_code_2": "BV",
        "iso_code_3": "BVT",
    },
    {
        "country": "Brazil",
        "full_name": "The Federative Republic of Brazil",
        "iso_code_2": "BR",
        "iso_code_3": "BRA",
    },
    {
        "country": "British Indian Ocean Territory",
        "full_name": "The British Indian Ocean Territory",
        "iso_code_2": "IO",
        "iso_code_3": "IOT",
    },
    {
        "country": "British Virgin Islands",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Virgin Islands (British)",
    },
    {
        "country": "Brunei Darussalam",
        "full_name": "The Nation of Brunei, the Abode of Peace",
        "iso_code_2": "BN",
        "iso_code_3": "BRN",
    },
    {
        "country": "Bulgaria",
        "full_name": "The Republic of Bulgaria",
        "iso_code_2": "BG",
        "iso_code_3": "BGR",
    },
    {
        "country": "Burkina Faso",
        "full_name": "Burkina Faso",
        "iso_code_2": "BF",
        "iso_code_3": "BFA",
    },
    {
        "country": "Burma",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Myanmar",
    },
    {
        "country": "Burundi",
        "full_name": "The Republic of Burundi",
        "iso_code_2": "BI",
        "iso_code_3": "BDI",
    },
    {
        "country": "Cabo Verde",
        "full_name": "The Republic of Cabo Verde",
        "iso_code_2": "CV",
        "iso_code_3": "CPV",
    },
    {
        "country": "Cambodia",
        "full_name": "The Kingdom of Cambodia",
        "iso_code_2": "KH",
        "iso_code_3": "KHM",
    },
    {
        "country": "Cameroon",
        "full_name": "The Republic of Cameroon",
        "iso_code_2": "CM",
        "iso_code_3": "CMR",
    },
    {
        "country": "Canada",
        "full_name": "Canada",
        "iso_code_2": "CA",
        "iso_code_3": "CAN",
    },
    {
        "country": "Cape Verde",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Cabo Verde",
    },
    {
        "country": " Caribbean Netherlands",
        "full_name": "Sint Eustatius and Saba.",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Bonaire",
    },
    {
        "country": "Cayman Islands",
        "full_name": "The Cayman Islands",
        "iso_code_2": "KY",
        "iso_code_3": "CYM",
    },
    {
        "country": "Central African Republic",
        "full_name": "The Central African Republic",
        "iso_code_2": "CF",
        "iso_code_3": "CAF",
    },
    {
        "country": "Chad",
        "full_name": "The Republic of Chad",
        "iso_code_2": "TD",
        "iso_code_3": "TCD",
    },
    {
        "country": "Chile",
        "full_name": "The Republic of Chile",
        "iso_code_2": "CL",
        "iso_code_3": "CHL",
    },
    {
        "country": "China",
        "full_name": "The People's Republic of China",
        "iso_code_2": "CN",
        "iso_code_3": "CHN",
    },
    {
        "country": "The Republic of China",
        "full_name": "The Republic of China",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Taiwan",
    },
    {
        "country": "Christmas Island",
        "full_name": "The Territory of Christmas Island",
        "iso_code_2": "CX",
        "iso_code_3": "CXR",
    },
    {
        "country": "Cocos Islands",
        "full_name": "The Territory of Cocos (Keeling) Islands",
        "iso_code_2": "CC",
        "iso_code_3": "CCK",
    },
    {
        "country": "Colombia",
        "full_name": "The Republic of Colombia",
        "iso_code_2": "CO",
        "iso_code_3": "COL",
    },
    {
        "country": "Comoros",
        "full_name": "The Union of the Comoros",
        "iso_code_2": "KM",
        "iso_code_3": "COM",
    },
    {
        "country": "Democratic Republic of the Congo",
        "full_name": "The Democratic Republic of the Congo",
        "iso_code_2": "CD",
        "iso_code_3": "COD",
    },
    {
        "country": "Congo",
        "full_name": "The Republic of the Congo",
        "iso_code_2": "CG",
        "iso_code_3": "COG",
    },
    {
        "country": "Cook Islands",
        "full_name": "The Cook Islands",
        "iso_code_2": "CK",
        "iso_code_3": "COK",
    },
    {
        "country": "Costa Rica",
        "full_name": "The Republic of Costa Rica",
        "iso_code_2": "CR",
        "iso_code_3": "CRI",
    },
    {
        "country": "Côte d'Ivoire",
        "full_name": "The Republic of Côte d'Ivoire",
        "iso_code_2": "CI",
        "iso_code_3": "CIV",
    },
    {
        "country": "Croatia",
        "full_name": "The Republic of Croatia",
        "iso_code_2": "HR",
        "iso_code_3": "HRV",
    },
    {
        "country": "Cuba",
        "full_name": "The Republic of Cuba",
        "iso_code_2": "CU",
        "iso_code_3": "CUB",
    },
    {
        "country": "Curaçao",
        "full_name": "The Country of Curaçao",
        "iso_code_2": "CW",
        "iso_code_3": "CUW",
    },
    {
        "country": "Cyprus",
        "full_name": "The Republic of Cyprus",
        "iso_code_2": "CY",
        "iso_code_3": "CYP",
    },
    {
        "country": "Czechia",
        "full_name": "The Czech Republic",
        "iso_code_2": "CZ",
        "iso_code_3": "CZE",
    },
    {
        "country": "Democratic People's Republic of Korea",
        "full_name": "The Democratic People's Republic of Korea",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Korea",
    },
    {
        "country": "Denmark",
        "full_name": "The Kingdom of Denmark",
        "iso_code_2": "DK",
        "iso_code_3": "DNK",
    },
    {
        "country": "Djibouti",
        "full_name": "The Republic of Djibouti",
        "iso_code_2": "DJ",
        "iso_code_3": "DJI",
    },
    {
        "country": "Dominica",
        "full_name": "The Commonwealth of Dominica",
        "iso_code_2": "DM",
        "iso_code_3": "DMA",
    },
    {
        "country": "Dominican Republic",
        "full_name": "The Dominican Republic",
        "iso_code_2": "DO",
        "iso_code_3": "DOM",
    },
    {
        "country": "East Timor",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Timor-Leste",
    },
    {
        "country": "Ecuador",
        "full_name": "The Republic of Ecuador",
        "iso_code_2": "EC",
        "iso_code_3": "ECU",
    },
    {
        "country": "Egypt",
        "full_name": "The Arab Republic of Egypt",
        "iso_code_2": "EG",
        "iso_code_3": "EGY",
    },
    {
        "country": "El Salvador",
        "full_name": "The Republic of El Salvador",
        "iso_code_2": "SV",
        "iso_code_3": "SLV",
    },
    {
        "country": "Equatorial Guinea",
        "full_name": "The Republic of Equatorial Guinea",
        "iso_code_2": "GQ",
        "iso_code_3": "GNQ",
    },
    {
        "country": "Eritrea",
        "full_name": "The State of Eritrea",
        "iso_code_2": "ER",
        "iso_code_3": "ERI",
    },
    {
        "country": "Estonia",
        "full_name": "The Republic of Estonia",
        "iso_code_2": "EE",
        "iso_code_3": "EST",
    },
    {
        "country": "Eswatini",
        "full_name": "The Kingdom of Eswatini",
        "iso_code_2": "SZ",
        "iso_code_3": "SWZ",
    },
    {
        "country": "Ethiopia",
        "full_name": "The Federal Democratic Republic of Ethiopia",
        "iso_code_2": "ET",
        "iso_code_3": "ETH",
    },
    {
        "country": "Falkland Islands",
        "full_name": "The Falkland Islands",
        "iso_code_2": "FK",
        "iso_code_3": "FLK",
    },
    {
        "country": "Faroe Islands",
        "full_name": "The Faroe Islands",
        "iso_code_2": "FO",
        "iso_code_3": "FRO",
    },
    {
        "country": "Fiji",
        "full_name": "The Republic of Fiji",
        "iso_code_2": "FJ",
        "iso_code_3": "FJI",
    },
    {
        "country": "Finland",
        "full_name": "The Republic of Finland",
        "iso_code_2": "FI",
        "iso_code_3": "FIN",
    },
    {
        "country": "France",
        "full_name": "The French Republic",
        "iso_code_2": "FR",
        "iso_code_3": "FRA",
    },
    {
        "country": "French Guiana",
        "full_name": "Guyane",
        "iso_code_2": "GF",
        "iso_code_3": "GUF",
    },
    {
        "country": "French Polynesia",
        "full_name": "French Polynesia",
        "iso_code_2": "PF",
        "iso_code_3": "PYF",
    },
    {
        "country": "French Southern Territories",
        "full_name": "The French Southern and Antarctic Lands",
        "iso_code_2": "TF",
        "iso_code_3": "ATF",
    },
    {
        "country": "Gabon",
        "full_name": "The Gabonese Republic",
        "iso_code_2": "GA",
        "iso_code_3": "GAB",
    },
    {
        "country": "Gambia",
        "full_name": "The Republic of The Gambia",
        "iso_code_2": "GM",
        "iso_code_3": "GMB",
    },
    {
        "country": "Georgia",
        "full_name": "Georgia",
        "iso_code_2": "GE",
        "iso_code_3": "GEO",
    },
    {
        "country": "Germany",
        "full_name": "The Federal Republic of Germany",
        "iso_code_2": "DE",
        "iso_code_3": "DEU",
    },
    {
        "country": "Ghana",
        "full_name": "The Republic of Ghana",
        "iso_code_2": "GH",
        "iso_code_3": "GHA",
    },
    {
        "country": "Gibraltar",
        "full_name": "Gibraltar",
        "iso_code_2": "GI",
        "iso_code_3": "GIB",
    },
    {
        "country": "Great Britain",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "United Kingdom",
    },
    {
        "country": "Greece",
        "full_name": "The Hellenic Republic",
        "iso_code_2": "GR",
        "iso_code_3": "GRC",
    },
    {
        "country": "Greenland",
        "full_name": "Kalaallit Nunaat",
        "iso_code_2": "GL",
        "iso_code_3": "GRL",
    },
    {
        "country": "Grenada",
        "full_name": "Grenada",
        "iso_code_2": "GD",
        "iso_code_3": "GRD",
    },
    {
        "country": "Guadeloupe",
        "full_name": "Guadeloupe",
        "iso_code_2": "GP",
        "iso_code_3": "GLP",
    },
    {
        "country": "Guam",
        "full_name": "The Territory of Guam",
        "iso_code_2": "GU",
        "iso_code_3": "GUM",
    },
    {
        "country": "Guatemala",
        "full_name": "The Republic of Guatemala",
        "iso_code_2": "GT",
        "iso_code_3": "GTM",
    },
    {
        "country": "Guernsey",
        "full_name": "The Bailiwick of Guernsey",
        "iso_code_2": "GG",
        "iso_code_3": "GGY",
    },
    {
        "country": "Guinea",
        "full_name": "The Republic of Guinea",
        "iso_code_2": "GN",
        "iso_code_3": "GIN",
    },
    {
        "country": "Guinea-Bissau",
        "full_name": "The Republic of Guinea-Bissau",
        "iso_code_2": "GW",
        "iso_code_3": "GNB",
    },
    {
        "country": "Guyana",
        "full_name": "The Co-operative Republic of Guyana",
        "iso_code_2": "GY",
        "iso_code_3": "GUY",
    },
    {
        "country": "Haiti",
        "full_name": "The Republic of Haiti",
        "iso_code_2": "HT",
        "iso_code_3": "HTI",
    },
    {
        "country": "Heard Island and McDonald Islands",
        "full_name": "The Territory of Heard Island and McDonald Islands",
        "iso_code_2": "HM",
        "iso_code_3": "HMD",
    },
    {
        "country": "Holy See",
        "full_name": "The Holy See",
        "iso_code_2": "VA",
        "iso_code_3": "VAT",
    },
    {
        "country": "Honduras",
        "full_name": "The Republic of Honduras",
        "iso_code_2": "HN",
        "iso_code_3": "HND",
    },
    {
        "country": "Hong Kong",
        "full_name": "The Hong Kong Special Administrative Region of China",
        "iso_code_2": "HK",
        "iso_code_3": "HKG",
    },
    {
        "country": "Hungary",
        "full_name": "Hungary",
        "iso_code_2": "HU",
        "iso_code_3": "HUN",
    },
    {
        "country": "Iceland",
        "full_name": "Iceland",
        "iso_code_2": "IS",
        "iso_code_3": "ISL",
    },
    {
        "country": "India",
        "full_name": "The Republic of India",
        "iso_code_2": "IN",
        "iso_code_3": "IND",
    },
    {
        "country": "Indonesia",
        "full_name": "The Republic of Indonesia",
        "iso_code_2": "ID",
        "iso_code_3": "IDN",
    },
    {
        "country": "Iran (Islamic Republic of)",
        "full_name": "The Islamic Republic of Iran",
        "iso_code_2": "IR",
        "iso_code_3": "IRN",
    },
    {
        "country": "Iraq",
        "full_name": "The Republic of Iraq",
        "iso_code_2": "IQ",
        "iso_code_3": "IRQ",
    },
    {
        "country": "Ireland",
        "full_name": "Ireland",
        "iso_code_2": "IE",
        "iso_code_3": "IRL",
    },
    {
        "country": "Isle of Man",
        "full_name": "The Isle of Man",
        "iso_code_2": "IM",
        "iso_code_3": "IMN",
    },
    {
        "country": "Israel",
        "full_name": "The State of Israel",
        "iso_code_2": "IL",
        "iso_code_3": "ISR",
    },
    {
        "country": "Italy",
        "full_name": "The Italian Republic",
        "iso_code_2": "IT",
        "iso_code_3": "ITA",
    },
    {
        "country": "Ivory Coast",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Côte d'Ivoire",
    },
    {
        "country": "Jamaica",
        "full_name": "Jamaica",
        "iso_code_2": "JM",
        "iso_code_3": "JAM",
    },
    {
        "country": "Jan Mayen",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Svalbard",
    },
    {
        "country": "Japan",
        "full_name": "Japan",
        "iso_code_2": "JP",
        "iso_code_3": "JPN"
    },
    {
        "country": "Jersey",
        "full_name": "The Bailiwick of Jersey",
        "iso_code_2": "JE",
        "iso_code_3": "JEY",
    },
    {
        "country": "Jordan",
        "full_name": "The Hashemite Kingdom of Jordan",
        "iso_code_2": "JO",
        "iso_code_3": "JOR",
    },
    {
        "country": "Kazakhstan",
        "full_name": "The Republic of Kazakhstan",
        "iso_code_2": "KZ",
        "iso_code_3": "KAZ",
    },
    {
        "country": "Kenya",
        "full_name": "The Republic of Kenya",
        "iso_code_2": "KE",
        "iso_code_3": "KEN",
    },
    {
        "country": "Kiribati",
        "full_name": "The Republic of Kiribati",
        "iso_code_2": "KI",
        "iso_code_3": "KIR",
    },
    {
        "country": "North Korea",
        "full_name": "The Democratic People's Republic of Korea",
        "iso_code_2": "KP",
        "iso_code_3": "PRK",
    },
    {
        "country": "South Korea",
        "full_name": "The Republic of Korea",
        "iso_code_2": "KR",
        "iso_code_3": "KOR",
    },
    {
        "country": "Kuwait",
        "full_name": "The State of Kuwait",
        "iso_code_2": "KW",
        "iso_code_3": "KWT",
    },
    {
        "country": "Kyrgyzstan",
        "full_name": "The Kyrgyz Republic",
        "iso_code_2": "KG",
        "iso_code_3": "KGZ",
    },
    {
        "country": "Laos",
        "full_name": "The Lao People's Democratic Republic",
        "iso_code_2": "LA",
        "iso_code_3": "LAO",
    },
    {
        "country": "Latvia",
        "full_name": "The Republic of Latvia",
        "iso_code_2": "LV",
        "iso_code_3": "LVA",
    },
    {
        "country": "Lebanon",
        "full_name": "The Lebanese Republic",
        "iso_code_2": "LB",
        "iso_code_3": "LBN",
    },
    {
        "country": "Lesotho",
        "full_name": "The Kingdom of Lesotho",
        "iso_code_2": "LS",
        "iso_code_3": "LSO",
    },
    {
        "country": "Liberia",
        "full_name": "The Republic of Liberia",
        "iso_code_2": "LR",
        "iso_code_3": "LBR",
    },
    {
        "country": "Libya",
        "full_name": "The State of Libya",
        "iso_code_2": "LY",
        "iso_code_3": "LBY",
    },
    {
        "country": "Liechtenstein",
        "full_name": "The Principality of Liechtenstein",
        "iso_code_2": "LI",
        "iso_code_3": "LIE",
    },
    {
        "country": "Lithuania",
        "full_name": "The Republic of Lithuania",
        "iso_code_2": "LT",
        "iso_code_3": "LTU",
    },
    {
        "country": "Luxembourg",
        "full_name": "The Grand Duchy of Luxembourg",
        "iso_code_2": "LU",
        "iso_code_3": "LUX",
    },
    {
        "country": "Macao",
        "full_name": "The Macao Special Administrative Region of China",
        "iso_code_2": "MO",
        "iso_code_3": "MAC",
    },
    {
        "country": "Madagascar",
        "full_name": "The Republic of Madagascar",
        "iso_code_2": "MG",
        "iso_code_3": "MDG",
    },
    {
        "country": "Malawi",
        "full_name": "The Republic of Malawi",
        "iso_code_2": "MW",
        "iso_code_3": "MWI",
    },
    {
        "country": "Malaysia",
        "full_name": "Malaysia",
        "iso_code_2": "MY",
        "iso_code_3": "MYS",
    },
    {
        "country": "Maldives",
        "full_name": "The Republic of Maldives",
        "iso_code_2": "MV",
        "iso_code_3": "MDV",
    },
    {
        "country": "Mali",
        "full_name": "The Republic of Mali",
        "iso_code_2": "ML",
        "iso_code_3": "MLI",
    },
    {
        "country": "Malta",
        "full_name": "The Republic of Malta",
        "iso_code_2": "MT",
        "iso_code_3": "MLT",
    },
    {
        "country": "Marshall Islands",
        "full_name": "The Republic of the Marshall Islands",
        "iso_code_2": "MH",
        "iso_code_3": "MHL",
    },
    {
        "country": "Martinique",
        "full_name": "Martinique",
        "iso_code_2": "MQ",
        "iso_code_3": "MTQ",
    },
    {
        "country": "Mauritania",
        "full_name": "The Islamic Republic of Mauritania",
        "iso_code_2": "MR",
        "iso_code_3": "MRT",
    },
    {
        "country": "Mauritius",
        "full_name": "The Republic of Mauritius",
        "iso_code_2": "MU",
        "iso_code_3": "MUS",
    },
    {
        "country": "Mayotte",
        "full_name": "The Department of Mayotte",
        "iso_code_2": "YT",
        "iso_code_3": "MYT",
    },
    {
        "country": "Mexico",
        "full_name": "The United Mexican States",
        "iso_code_2": "MX",
        "iso_code_3": "MEX",
    },
    {
        "country": "Micronesia (Federated States of)",
        "full_name": "The Federated States of Micronesia",
        "iso_code_2": "FM",
        "iso_code_3": "FSM",
    },
    {
        "country": "Moldova (the Republic of)",
        "full_name": "The Republic of Moldova",
        "iso_code_2": "MD",
        "iso_code_3": "MDA",
    },
    {
        "country": "Monaco",
        "full_name": "The Principality of Monaco",
        "iso_code_2": "MC",
        "iso_code_3": "MCO",
    },
    {
        "country": "Mongolia",
        "full_name": "Mongolia",
        "iso_code_2": "MN",
        "iso_code_3": "MNG",
    },
    {
        "country": "Montenegro",
        "full_name": "Montenegro",
        "iso_code_2": "ME",
        "iso_code_3": "MNE",
    },
    {
        "country": "Montserrat",
        "full_name": "Montserrat",
        "iso_code_2": "MS",
        "iso_code_3": "MSR",
    },
    {
        "country": "Morocco",
        "full_name": "The Kingdom of Morocco",
        "iso_code_2": "MA",
        "iso_code_3": "MAR",
    },
    {
        "country": "Mozambique",
        "full_name": "The Republic of Mozambique",
        "iso_code_2": "MZ",
        "iso_code_3": "MOZ",
    },
    {
        "country": "Myanmar",
        "full_name": "The Republic of the Union of Myanmar",
        "iso_code_2": "MM",
        "iso_code_3": "MMR",
    },
    {
        "country": "Namibia",
        "full_name": "The Republic of Namibia",
        "iso_code_2": "NA",
        "iso_code_3": "NAM",
    },
    {
        "country": "Nauru",
        "full_name": "The Republic of Nauru",
        "iso_code_2": "NR",
        "iso_code_3": "NRU",
    },
    {
        "country": "Nepal",
        "full_name": "The Federal Democratic Republic of Nepal",
        "iso_code_2": "NP",
        "iso_code_3": "NPL",
    },
    {
        "country": "Netherlands",
        "full_name": "The Kingdom of the Netherlands",
        "iso_code_2": "NL",
        "iso_code_3": "NLD",
    },
    {
        "country": "New Caledonia",
        "full_name": "New Caledonia",
        "iso_code_2": "NC",
        "iso_code_3": "NCL",
    },
    {
        "country": "New Zealand",
        "full_name": "New Zealand",
        "iso_code_2": "NZ",
        "iso_code_3": "NZL",
    },
    {
        "country": "Nicaragua",
        "full_name": "The Republic of Nicaragua",
        "iso_code_2": "NI",
        "iso_code_3": "NIC",
    },
    {
        "country": "Niger",
        "full_name": "The Republic of the Niger",
        "iso_code_2": "NE",
        "iso_code_3": "NER",
    },
    {
        "country": "Nigeria",
        "full_name": "The Federal Republic of Nigeria",
        "iso_code_2": "NG",
        "iso_code_3": "NGA",
    },
    {
        "country": "Niue",
        "full_name": "Niue",
        "iso_code_2": "NU",
        "iso_code_3": "NIU"
    },
    {
        "country": "Norfolk Island",
        "full_name": "The Territory of Norfolk Island",
        "iso_code_2": "NF",
        "iso_code_3": "NFK",
    },
    {
        "country": "The Democratic People's Republic of Korea",
        "full_name": "The Democratic People's Republic of Korea.",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "North Korea",
    },
    {
        "country": "North Macedonia",
        "full_name": "The Republic of North Macedonia",
        "iso_code_2": "MK",
        "iso_code_3": "MKD",
    },
    {
        "country": "Northern Mariana Islands",
        "full_name": "The Commonwealth of the Northern Mariana Islands",
        "iso_code_2": "MP",
        "iso_code_3": "MNP",
    },
    {
        "country": "Norway",
        "full_name": "The Kingdom of Norway",
        "iso_code_2": "NO",
        "iso_code_3": "NOR",
    },
    {
        "country": "Oman",
        "full_name": "The Sultanate of Oman",
        "iso_code_2": "OM",
        "iso_code_3": "OMN",
    },
    {
        "country": "Pakistan",
        "full_name": "The Islamic Republic of Pakistan",
        "iso_code_2": "PK",
        "iso_code_3": "PAK",
    },
    {
        "country": "Palau",
        "full_name": "The Republic of Palau",
        "iso_code_2": "PW",
        "iso_code_3": "PLW",
    },
    {
        "country": " Palestine",
        "full_name": "The State of Palestine",
        "iso_code_2": "PS",
        "iso_code_3": "PSE",
    },
    {
        "country": "Panama",
        "full_name": "The Republic of Panamá",
        "iso_code_2": "PA",
        "iso_code_3": "PAN",
    },
    {
        "country": "Papua New Guinea",
        "full_name": "The Independent State of Papua New Guinea",
        "iso_code_2": "PG",
        "iso_code_3": "PNG",
    },
    {
        "country": "Paraguay",
        "full_name": "The Republic of Paraguay",
        "iso_code_2": "PY",
        "iso_code_3": "PRY",
    },
    {
        "country": "People's Republic of China",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "China",
    },
    {
        "country": "Peru",
        "full_name": "The Republic of Perú",
        "iso_code_2": "PE",
        "iso_code_3": "PER",
    },
    {
        "country": "Philippines",
        "full_name": "The Republic of the Philippines",
        "iso_code_2": "PH",
        "iso_code_3": "PHL",
    },
    {
        "country": "Pitcairn",
        "full_name": "The Pitcairn, Henderson, Ducie and Oeno Islands",
        "iso_code_2": "PN",
        "iso_code_3": "PCN",
    },
    {
        "country": "Poland",
        "full_name": "The Republic of Poland",
        "iso_code_2": "PL",
        "iso_code_3": "POL",
    },
    {
        "country": "Portugal",
        "full_name": "The Portuguese Republic",
        "iso_code_2": "PT",
        "iso_code_3": "PRT",
    },
    {
        "country": "Puerto Rico",
        "full_name": "The Commonwealth of Puerto Rico",
        "iso_code_2": "PR",
        "iso_code_3": "PRI",
    },
    {
        "country": "Qatar",
        "full_name": "The State of Qatar",
        "iso_code_2": "QA",
        "iso_code_3": "QAT",
    },
    {
        "country": "Republic of China",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Taiwan",
    },
    {
        "country": "Republic of Korea",
        "full_name": "The Republic of Korea",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "South Korea",
    },
    {
        "country": "Republic of the Congo",
        "full_name": "The Republic of the Congo",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Congo",
    },
    {
        "country": "Réunion",
        "full_name": "Réunion",
        "iso_code_2": "RE",
        "iso_code_3": "REU",
    },
    {
        "country": "Romania",
        "full_name": "Romania",
        "iso_code_2": "RO",
        "iso_code_3": "ROU",
    },
    {
        "country": "Russian Federation",
        "full_name": "The Russian Federation",
        "iso_code_2": "RU",
        "iso_code_3": "RUS",
    },
    {
        "country": "Rwanda",
        "full_name": "The Republic of Rwanda",
        "iso_code_2": "RW",
        "iso_code_3": "RWA",
    },
    {
        "country": "Saba",
        "full_name": "Sint Eustatius and Saba",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Bonaire",
    },
    {
        "country": "Sahrawi Arab Democratic Republic",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Western Sahara",
    },
    {
        "country": "Saint Barthélemy",
        "full_name": "The Collectivity of Saint-Barthélemy",
        "iso_code_2": "BL",
        "iso_code_3": "BLM",
    },
    {
        "country": "Saint Helena",
        "full_name": "Saint Helena, Ascension and Tristan da Cunha",
        "iso_code_2": "SH",
        "iso_code_3": "SHN",
    },
    {
        "country": "Ascension Island",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
    },
    {
        "country": "Tristan da Cunha",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
    },
    {
        "country": "Saint Kitts and Nevis",
        "full_name": "Saint Kitts and Nevis",
        "iso_code_2": "KN",
        "iso_code_3": "KNA",
    },
    {
        "country": "Saint Lucia",
        "full_name": "Saint Lucia",
        "iso_code_2": "LC",
        "iso_code_3": "LCA",
    },
    {
        "country": "Saint Martin (French part)",
        "full_name": "The Collectivity of Saint-Martin",
        "iso_code_2": "MF",
        "iso_code_3": "MAF",
    },
    {
        "country": "Saint Pierre and Miquelon",
        "full_name": "The Overseas Collectivity of Saint-Pierre and Miquelon",
        "iso_code_2": "PM",
        "iso_code_3": "SPM",
    },
    {
        "country": "Saint Vincent and the Grenadines",
        "full_name": "Saint Vincent and the Grenadines",
        "iso_code_2": "VC",
        "iso_code_3": "VCT",
    },
    {
        "country": "Samoa",
        "full_name": "The Independent State of Samoa",
        "iso_code_2": "WS",
        "iso_code_3": "WSM",
    },
    {
        "country": "San Marino",
        "full_name": "The Republic of San Marino",
        "iso_code_2": "SM",
        "iso_code_3": "SMR",
    },
    {
        "country": "Sao Tome and Principe",
        "full_name": "The Democratic Republic of São Tomé and Príncipe",
        "iso_code_2": "ST",
        "iso_code_3": "STP",
    },
    {
        "country": "Saudi Arabia",
        "full_name": "The Kingdom of Saudi Arabia",
        "iso_code_2": "SA",
        "iso_code_3": "SAU",
    },
    {
        "country": "Senegal",
        "full_name": "The Republic of Senegal",
        "iso_code_2": "SN",
        "iso_code_3": "SEN",
    },
    {
        "country": "Serbia",
        "full_name": "The Republic of Serbia",
        "iso_code_2": "RS",
        "iso_code_3": "SRB",
    },
    {
        "country": "Seychelles",
        "full_name": "The Republic of Seychelles",
        "iso_code_2": "SC",
        "iso_code_3": "SYC",
    },
    {
        "country": "Sierra Leone",
        "full_name": "The Republic of Sierra Leone",
        "iso_code_2": "SL",
        "iso_code_3": "SLE",
    },
    {
        "country": "Singapore",
        "full_name": "The Republic of Singapore",
        "iso_code_2": "SG",
        "iso_code_3": "SGP",
    },
    {
        "country": "Sint Eustatius",
        "full_name": "Sint Eustatius and Saba",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Bonaire",
    },
    {
        "country": "Sint Maarten (Dutch part)",
        "full_name": "Sint Maarten",
        "iso_code_2": "SX",
        "iso_code_3": "SXM",
    },
    {
        "country": "Slovakia",
        "full_name": "The Slovak Republic",
        "iso_code_2": "SK",
        "iso_code_3": "SVK",
    },
    {
        "country": "Slovenia",
        "full_name": "The Republic of Slovenia",
        "iso_code_2": "SI",
        "iso_code_3": "SVN",
    },
    {
        "country": "Solomon Islands",
        "full_name": "The Solomon Islands",
        "iso_code_2": "SB",
        "iso_code_3": "SLB",
    },
    {
        "country": "Somalia",
        "full_name": "The Federal Republic of Somalia",
        "iso_code_2": "SO",
        "iso_code_3": "SOM",
    },
    {
        "country": "South Africa",
        "full_name": "The Republic of South Africa",
        "iso_code_2": "ZA",
        "iso_code_3": "ZAF",
    },
    {
        "country": "South Georgia and the South Sandwich Islands",
        "full_name": "South Georgia and the South Sandwich Islands",
        "iso_code_2": "GS",
        "iso_code_3": "SGS",
    },
    {
        "country": "South Korea",
        "full_name": "The Republic of South Korea",
        "iso_code_2": "",
        "iso_code_3": "",
    },
    {
        "country": "South Sudan",
        "full_name": "The Republic of South Sudan",
        "iso_code_2": "SS",
        "iso_code_3": "SSD",
    },
    {
        "country": "Spain",
        "full_name": "The Kingdom of Spain",
        "iso_code_2": "ES",
        "iso_code_3": "ESP",
    },
    {
        "country": "Sri Lanka",
        "full_name": "The Democratic Socialist Republic of Sri Lanka",
        "iso_code_2": "LK",
        "iso_code_3": "LKA",
    },
    {
        "country": "Sudan",
        "full_name": "The Republic of the Sudan",
        "iso_code_2": "SD",
        "iso_code_3": "SDN",
    },
    {
        "country": "Suriname",
        "full_name": "The Republic of Suriname",
        "iso_code_2": "SR",
        "iso_code_3": "SUR",
    },
    {
        "country": "Svalbard",
        "full_name": "Svalbard and Jan Mayen",
        "iso_code_2": "SJ",
        "iso_code_3": "SJM",
    },
    {
        "country": "Jan Mayen",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": ""
    },
    {
        "country": "Sweden",
        "full_name": "The Kingdom of Sweden",
        "iso_code_2": "SE",
        "iso_code_3": "SWE",
    },
    {
        "country": "Switzerland",
        "full_name": "The Swiss Confederation",
        "iso_code_2": "CH",
        "iso_code_3": "CHE",
    },
    {
        "country": "Syrian Arab Republic",
        "full_name": "The Syrian Arab Republic",
        "iso_code_2": "SY",
        "iso_code_3": "SYR",
    },
    {
        "country": "Taiwan",
        "full_name": "The Republic of China",
        "iso_code_2": "TW",
        "iso_code_3": "TWN",
    },
    {
        "country": "Tajikistan",
        "full_name": "The Republic of Tajikistan",
        "iso_code_2": "TJ",
        "iso_code_3": "TJK",
    },
    {
        "country": " Tanzania",
        "full_name": "The United Republic of Tanzania",
        "iso_code_2": "TZ",
        "iso_code_3": "TZA",
    },
    {
        "country": "Thailand",
        "full_name": "The Kingdom of Thailand",
        "iso_code_2": "TH",
        "iso_code_3": "THA",
    },
    {
        "country": "Timor-Leste",
        "full_name": "The Democratic Republic of Timor-Leste",
        "iso_code_2": "TL",
        "iso_code_3": "TLS",
    },
    {
        "country": "Togo",
        "full_name": "The Togolese Republic",
        "iso_code_2": "TG",
        "iso_code_3": "TGO",
    },
    {
        "country": "Tokelau",
        "full_name": "Tokelau",
        "iso_code_2": "TK",
        "iso_code_3": "TKL",
    },
    {
        "country": "Tonga",
        "full_name": "The Kingdom of Tonga",
        "iso_code_2": "TO",
        "iso_code_3": "TON",
    },
    {
        "country": "Trinidad and Tobago",
        "full_name": "The Republic of Trinidad and Tobago",
        "iso_code_2": "TT",
        "iso_code_3": "TTO",
    },
    {
        "country": "Tunisia",
        "full_name": "The Republic of Tunisia",
        "iso_code_2": "TN",
        "iso_code_3": "TUN",
    },
    {
        "country": "Türkiye [ac]",
        "full_name": "The Republic of Türkiye",
        "iso_code_2": "TR",
        "iso_code_3": "TUR",
    },
    {
        "country": "Turkmenistan",
        "full_name": "Turkmenistan",
        "iso_code_2": "TM",
        "iso_code_3": "TKM",
    },
    {
        "country": "Turks and Caicos Islands",
        "full_name": "The Turks and Caicos Islands",
        "iso_code_2": "TC",
        "iso_code_3": "TCA",
    },
    {
        "country": "Tuvalu",
        "full_name": "Tuvalu",
        "iso_code_2": "TV",
        "iso_code_3": "TUV",
    },
    {
        "country": "Uganda",
        "full_name": "The Republic of Uganda",
        "iso_code_2": "UG",
        "iso_code_3": "UGA",
    },
    {
        "country": "Ukraine",
        "full_name": "Ukraine",
        "iso_code_2": "UA",
        "iso_code_3": "UKR",
    },
    {
        "country": "United Arab Emirates",
        "full_name": "The United Arab Emirates",
        "iso_code_2": "AE",
        "iso_code_3": "ARE",
    },
    {
        "country": "United Kingdom",
        "full_name": "The United Kingdom",
        "iso_code_2": "GB",
        "iso_code_3": "GBR",
        "map_to": "United Kingdom of Great Britain and Northern Ireland"

    },
    {
        "country": "United Kingdom of Great Britain and Northern Ireland",
        "full_name": "The United Kingdom of Great Britain and Northern Ireland",
        "iso_code_2": "GB",
        "iso_code_3": "GBR",
    },
    {
        "country": "United States Minor Outlying Islands",
        "full_name": "Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island",
        "iso_code_2": "UM",
        "iso_code_3": "UMI",
    },
    {
        "country": "United States of America",
        "full_name": "The United States of America",
        "iso_code_2": "US",
        "iso_code_3": "USA",
    },
    {
        "country": "United States Virgin Islands",
        "full_name": "",
        "iso_code_2": "",
        "iso_code_3": "",
        "map_to": "Virgin Islands (U.S.)",
    },
    {
        "country": "Uruguay",
        "full_name": "The Oriental Republic of Uruguay",
        "iso_code_2": "UY",
        "iso_code_3": "URY",
    },
    {
        "country": "Uzbekistan",
        "full_name": "The Republic of Uzbekistan",
        "iso_code_2": "UZ",
        "iso_code_3": "UZB",
    },
    {
        "country": "Vanuatu",
        "full_name": "The Republic of Vanuatu",
        "iso_code_2": "VU",
        "iso_code_3": "VUT",
    },
    {
        "country": "Vatican City",
        "full_name": "The Vatican City",
        "iso_code_2": "",
        "iso_code_3": "",
    },
    {
        "country": "Venezuela",
        "full_name": "The Bolivarian Republic of Venezuela",
        "iso_code_2": "VE",
        "iso_code_3": "VEN",
    },
    {
        "country": "Viet Nam",
        "full_name": "The Socialist Republic of Viet Nam",
        "iso_code_2": "VN",
        "iso_code_3": "VNM",
    },
    {
        "country": "Virgin Islands (British)",
        "full_name": "The Virgin Islands",
        "iso_code_2": "VG",
        "iso_code_3": "VGB",
    },
    {
        "country": "Virgin Islands (U.S.)",
        "full_name": "The Virgin Islands of the United States",
        "iso_code_2": "VI",
        "iso_code_3": "VIR",
    },
    {
        "country": "Wallis and Futuna",
        "full_name": "The Territory of the Wallis and Futuna Islands",
        "iso_code_2": "WF",
        "iso_code_3": "WLF",
    },
    {
        "country": "Western Sahara",
        "full_name": "The Sahrawi Arab Democratic Republic",
        "iso_code_2": "EH",
        "iso_code_3": "ESH",
    },
    {
        "country": "Yemen",
        "full_name": "The Republic of Yemen",
        "iso_code_2": "YE",
        "iso_code_3": "YEM",
    },
    {
        "country": "Zambia",
        "full_name": "The Republic of Zambia",
        "iso_code_2": "ZM",
        "iso_code_3": "ZMB",
    },
    {
        "country": "Zimbabwe",
        "full_name": "The Republic of Zimbabwe",
        "iso_code_2": "ZW",
        "iso_code_3": "ZWE",
    },
]
